//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchivumU.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;

        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchivumU.I18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static event EventHandler CultureChanged;
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
                CultureChanged?.Invoke(null, EventArgs.Empty); 
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string _About {
            get {
                return ResourceManager.GetString("_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string _Add {
            get {
                return ResourceManager.GetString("_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Backups.
        /// </summary>
        public static string _auto_backups {
            get {
                return ResourceManager.GetString("_auto_backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Connect.
        /// </summary>
        public static string _auto_connect {
            get {
                return ResourceManager.GetString("_auto_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup To Local.
        /// </summary>
        public static string _BackupToLocal {
            get {
                return ResourceManager.GetString("_BackupToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string _block {
            get {
                return ResourceManager.GetString("_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new block.
        /// </summary>
        public static string _block_create {
            get {
                return ResourceManager.GetString("_block_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete block.
        /// </summary>
        public static string _block_del {
            get {
                return ResourceManager.GetString("_block_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low-level formatting(write 0x00).
        /// </summary>
        public static string _block_lformat {
            get {
                return ResourceManager.GetString("_block_lformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh block.
        /// </summary>
        public static string _block_refresh {
            get {
                return ResourceManager.GetString("_block_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename block.
        /// </summary>
        public static string _block_rename {
            get {
                return ResourceManager.GetString("_block_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string _Chinese {
            get {
                return ResourceManager.GetString("_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string _config {
            get {
                return ResourceManager.GetString("_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string _device {
            get {
                return ResourceManager.GetString("_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string _English {
            get {
                return ResourceManager.GetString("_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string _Exit {
            get {
                return ResourceManager.GetString("_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string _File {
            get {
                return ResourceManager.GetString("_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string _Help {
            get {
                return ResourceManager.GetString("_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string _key {
            get {
                return ResourceManager.GetString("_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new key and value.
        /// </summary>
        public static string _key_create {
            get {
                return ResourceManager.GetString("_key_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Key.
        /// </summary>
        public static string _key_remove {
            get {
                return ResourceManager.GetString("_key_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string _Language {
            get {
                return ResourceManager.GetString("_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string _More {
            get {
                return ResourceManager.GetString("_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string _Refresh {
            get {
                return ResourceManager.GetString("_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string _Remove {
            get {
                return ResourceManager.GetString("_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string _Rename {
            get {
                return ResourceManager.GetString("_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string _Save {
            get {
                return ResourceManager.GetString("_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveAs.
        /// </summary>
        public static string _SaveAs {
            get {
                return ResourceManager.GetString("_SaveAs", resourceCulture);
            }
        }
    }
}
